### ISSUE TITLE
DANE configuration

### ISSUE THREAD

**Issue by morki** [mjl-/mox#185]
When I test settings in mox admin, it shows DANE: OK:

![image](https://github.com/mjl-/mox/assets/3584190/d471c215-da29-4670-977e-fc2fbea1a198)

But when I click the link in bottom `Check configuration at internet.nl`, it shows DANE is not configured.

https://internet.nl/mail/morki.cz/1277684/

Do I need to do something manually?

**Comment by mjl-** [comment]
Hi @morki, indeed this doesn't look helpful.
Could it be that the public listener in mox.conf doesn't have host keys? For example, my mox.conf has this:

```
Listeners:
        public:
                TLS:
                        HostPrivateKeyFiles:
                                - hostkeys/mail.axillis.nl.20231009T215235.rsa2048.privatekey.pkcs8.pem
                                - hostkeys/mail.axillis.nl.20231009T215235.ecdsap256.privatekey.pkcs8.pem
```

If the "HostPrivateKeyFiles" isn't present, then mox currently isn't expecting to find any DANE records, which could be the reason it's claiming all is good.
It could also be that mox is doing MX lookups and not getting any records for a domain. That could perhaps happen if the entire domain was set up just now, and a dns cache still has the "no mx records exist" present in its cache.

Are you seeing the "Show instructions" link like on the included screenshot? If not, it's probably a case of missing host keys. See command "mox config ensureacmehostprivatekeys" for creating these host keys, https://pkg.go.dev/github.com/mjl-/mox#hdr-mox_config_ensureacmehostprivatekeys. After they are created, the mox dnscheck should show instructions and say that records are missing. This should only be necessary if you initially installed mox some time ago, when DANE wasn't implemented yet. If this is needed on a fresh new install, I would have to look into that.

![image](https://github.com/mjl-/mox/assets/1684740/aa7914ef-c087-4ac9-9050-a112417cdbbf)

I think we should change the dns check page to display a yellow "Not configured" instead of "OK" if no host keys are configured.
