### ISSUE TITLE
custom certificate file and key

### ISSUE THREAD

**Issue by hismailbulut** [mjl-/mox#2]
Hi, first of all thank you for this great project.

I am trying to use mox on my vps with an api already serving at http and https ports. I want to use both of them at same server. I started mox with `mox quickstart mail@mydomain.com` and edited the mox.conf as suggested at docs and replaced tls config with my certificate file path and private key. The mox works well if I use ACME but it panics when I change it like this:
```yaml
DataDir: ../data
LogLevel: error
Hostname: mail.mydomain.com
CheckUpdates: true
AdminPasswordFile: adminpasswd

Listeners:
  internal:
    IPs:
      - 127.0.0.1
      - ::1
      - <some other public ip's>
    Hostname: localhost
    TLS:
      ACME: letsencrypt
      KeyCerts:
        - 
          CertFile: /path/to/the/cert
          KeyFile: /path/to/the/key
    SMTPMaxMessageSize: 1048576
    AccountHTTP:
      Enabled: false
    AdminHTTP:
      Enabled: false
    MetricsHTTP:
      Enabled: false
  public:
    IPs:
      - 0.0.0.0
      - ::
    TLS:
      ACME: letsencrypt
    SMTP:
      Enabled: true
    Submissions:
      Enabled: true
    IMAPS:
      Enabled: true
    AutoconfigHTTPS:
      Enabled: false
    MTASTSHTTPS:
      Enabled: false
Postmaster:
  Account: mail
  Mailbox: Postmaster
```
And this is the panic message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8e1c62]

goroutine 1 [running]:
github.com/mjl-/mox/mox-.PrepareStaticConfig({0x0?, 0x0?}, {0xca4e52, 0xf}, 0xc0000bd900, 0x0)
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/mox-/config.go:440 +0xf42
github.com/mjl-/mox/mox-.ParseConfig({0xddcd58, 0xc000038080}, {0xca4e52, 0xf}, 0x0)
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/mox-/config.go:347 +0x52c
github.com/mjl-/mox/mox-.LoadConfig({0xddcd58?, 0xc000038080?})
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/mox-/config.go:310 +0x4e
github.com/mjl-/mox/mox-.MustLoadConfig()
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/mox-/config.go:295 +0xc5
main.cmdServe(0xc0000b6f80)
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/serve.go:135 +0x7c
main.main()
        /home/bulutlinux/go/pkg/mod/github.com/mjl-/mox@v0.0.1/main.go:407 +0x922
```
It doesnt panic if I change the line after KeyCerts to something like this 
```yaml
KeyCerts:
  - cert:
```
but this time it gives this error:
```
fatal: "loading config file": "parsing config/mox.conf: :<line number of "- cert:">: expected indent" (pkg: mox)
```

**Comment by mjl-** [comment]
Thanks for the report! I'll look into why that panic is happening. But if you aren't using ACME, you should remove the "ACME: letsencrypt" lines. That may already get you further.

And the reason it doesn't panic with your KeyCerts change is that it makes the configuration file invalid (invalid syntax), so it never makes it to the code that panics. The syntax may look a bit weird, this isn't yaml, so you really need to use something like this:

```
      KeyCerts:
        - 
          CertFile: /path/to/the/cert
          KeyFile: /path/to/the/key
```
