### ISSUE TITLE
Improve docker support

### ISSUE THREAD

**Issue by conformist-mw** [mjl-/mox#24]
First of all, I want to express my gratitude for this project. I was able to configure everything without using docker, it's really cool.

Now I would like to explain my use-case and ask if it is possible to do so as part of this project.

The main idea is to run the project in a docker and allow to proxy web traffic through traefik (or nginx, if someone wants to).

Because the project has to be started with `network_mode: "host"`, it becomes very difficult to accomplish this task.

Here's an example of how I would like it to work (it's Ansible config, but the main idea is just to run docker container with needed configuration):

```yaml
- name: Run mail container
  community.docker.docker_container:
    image: r.xmox.nl/mox:latest
    name: mox
    restart: true
    restart_policy: "unless-stopped"
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - "{{ data_dir }}/mox/config:/mox/config"
      - "{{ data_dir }}/mox/data:/mox/data"
      - "{{ data_dir }}/mox/web:/mox/web"
      - "{{ server_dir }}/letsencrypt/certs/:/mox/certs:ro"
    env:
      MOX_DOCKER: "yes"
    working_dir: "/mox"
    labels:
      traefik.enable: "true"
      traefik.http.routers.moxauto.tls: "true"
      traefik.http.routers.moxauto.entrypoints: "websecure"
      traefik.http.routers.moxauto.tls.certresolver: "letsencrypt"
      traefik.http.routers.moxauto.rule: "Host(`autoconfig.{{ ansible_host }}`,`mta-sts.{{ ansible_host }}`)"
      traefik.http.routers.moxauto.middlewares: "no-auth-chain@file"
      traefik.http.routers.moxauto.service: "moxauto"
      traefik.http.services.moxauto.loadbalancer.server.port: "81"
      traefik.http.routers.mox.tls: "true"
      traefik.http.routers.mox.entrypoints: "websecure"
      traefik.http.routers.mox.tls.certresolver: "letsencrypt"
      traefik.http.routers.mox.rule: "Host(`mail.{{ ansible_host }}`)"
      traefik.http.routers.mox.middlewares: "auth-chain@file"
      traefik.http.routers.mox.service: "mox"
      traefik.http.services.mox.loadbalancer.server.port: "1080"
```
Thus, we explicitly specify the ports that need to be opened for the mail to work properly. 
For web control and autoconfig requests, we proxy requests using traefik (autoconfig, mta-sts -> 81, web panel -> 1080). traefik here will get the certificates itself, we only need to provide a certificate for the mail services.
