### ISSUE TITLE
Handler for Internal Webmail shows Admin Service on reload

### ISSUE THREAD

**Issue by kiekerjan** [mjl-/mox#264]
I have a Handler configured:

```
WebHandlers:
...
                WebInternal:
                        BasePath: /
                        Service: webmail
```

On reload of the Webserver config window, the service dropdown is populated with Admin, instead of Webmail. If you don´t change this and press Save, the configuration is changed to `Service: admin`
