### ISSUE TITLE
Unable to configure WebserverHTTP on port 1080 and WebserverHTTPS on port 1443

### ISSUE THREAD

**Issue by nicolasdanelon** [mjl-/mox#313]
Hey there! I’m new to Mox!

I cannot get it running when I try to run WebserverHTTP on port 1080 and WebserverHTTPS on port 1443, since the default HTTP and HTTPS ports are already used by my Nginx.

btw, my real ip address is not 66.666.666.666 and my domain is not mail.lalala.ar. haha, those are just for github.

`journalctl -f -u mox.service`

```
Mar 17 10:44:19 mail.lalala.ar systemd[1]: Started mox mail server.
Mar 17 10:44:19 mail.lalala.ar mox[52599]: l=debug m="autotls setting allowed hostnames" pkg=mox hostnames=[autoconfig.lalala.ar;mail.lalala.ar;mta-sts.lalala.ar] publicips=[66.666.666.666]
Mar 17 10:44:19 mail.lalala.ar mox[52599]: l=print m="starting as root, initializing network listeners" pkg=serve version=v0.0.14-go1.24.1 pid=52599 moxconf=/home/mox/config/mox.conf domainsconf=/home/mox/config/domains.conf
Mar 17 10:44:19 mail.lalala.ar mox[52599]: l=print m="listening for smtp" pkg=smtpserver listener=public address=66.666.666.666:25 protocol=smtp
Mar 17 10:44:19 mail.lalala.ar mox[52599]: l=print m="listening for smtp" pkg=smtpserver listener=public address=66.666.666.666:465 protocol=submissions
Mar 17 10:44:19 mail.lalala.ar mox[52599]: l=print m="listening for imap" pkg=imapserver listener=public addr=66.666.666.666:993 protocol=imaps
Mar 17 10:44:19 mail.lalala.ar mox[52599]: l=print m="http listener" pkg=http name=internal kinds="account-http at /,admin-http at /admin/,webapi-http at /webapi/,webmail-http at /webmail/" address=10.66.66.1:80
Mar 17 10:44:19 mail.lalala.ar mox[52599]: l=fatal m="http: listen" err="listen tcp4 10.66.66.1:80: bind: address already in use" pkg=http addr=10.66.66.1:80
Mar 17 10:44:19 mail.lalala.ar systemd[1]: mox.service: Main process exited, code=exited, status=1/FAILURE
Mar 17 10:44:19 mail.lalala.ar systemd[1]: mox.service: Failed with result 'exit-code'.
```

as you can see the config file is `/home/mox/config/domains.conf` with the following content:

```
DataDir: ../data
LogLevel: debug
User: mox
Hostname: mail.lalala.ar
ACME:
        letsencrypt:
                DirectoryURL: https://acme-v02.api.letsencrypt.org/directory
                ContactEmail: postmaster@lalala.ar
                IssuerDomainName: letsencrypt.org
AdminPasswordFile: adminpasswd
Listeners:
        internal:
                IPs:
                        - 10.66.66.1
                        - fd42:42:42::1
                        - 127.0.0.1
                        - ::1
                Hostname: localhost
                AccountHTTP:
                        Enabled: true
                AdminHTTP:
                        Enabled: true
                WebmailHTTP:
                        Enabled: true
                WebAPIHTTP:
                        Enabled: true
                MetricsHTTP:
                        Enabled: true
        public:
                IPs:
                        - 66.666.666.666
                TLS:
                        ACME: letsencrypt
                        HostPrivateKeyFiles:
                                - hostkeys/mail.lalala.ar.20250313T122837.rsa2048.privatekey.pkcs8.pem
                                - hostkeys/mail.lalala.ar.20250313T122837.ecdsap256.privatekey.pkcs8.pem
                SMTP:
                        Enabled: true
                Submissions:
                        Enabled: true
                IMAPS:
                        Enabled: true
                AutoconfigHTTPS:
                        Enabled: true
                MTASTSHTTPS:
                        Enabled: true
                WebserverHTTP:
                        Enabled: true
                        Port: 1080
                WebserverHTTPS:
                        Enabled: true
                        Port: 1443
Postmaster:
        Account: postmaster
        Mailbox: Postmaster
HostTLSRPT:
        Account: postmaster
        Mailbox: TLSRPT
        Localpart: tls-reports
```

At this point I'm creating an issue cuz I cannot make it work and I supposed to be configuring it right, right?
thanks in advance!

**Comment by mjl-** [comment]
Hi nicolasdanelon!

> listen tcp4 10.66.66.1:80: bind: address already in use

```
        internal:
                IPs:
                        - 10.66.66.1
                        - fd42:42:42::1
                        - 127.0.0.1
                        - ::1
                Hostname: localhost
                AccountHTTP:
                        Enabled: true
                AdminHTTP:
                        Enabled: true
                WebmailHTTP:
                        Enabled: true
                WebAPIHTTP:
                        Enabled: true
                MetricsHTTP:
                        Enabled: true
```

These HTTP interfaces listen on port 80 by default. They need a `Port: 1080` too. Or nginx could be configured to no longer listen on these internal/loopback IPs, to free up the port.

About the public IP: You may not actually need the HTTPS-variant of Webserver? Assuming nginx is handling that and you're reverse proxying the requests from nginx to mox without TLS. And for AutoconfigHTTPS and MTASTSHTTPS you probably want to reverse proxy in plain HTTP instead of HTTPS too. If so, you'll need the `NonTLS: true` option, see https://www.xmox.nl/config/#cfg-mox-conf-Listeners-x-AutoconfigHTTPS-NonTLS.

```
                AutoconfigHTTPS:
                        Enabled: true
                MTASTSHTTPS:
                        Enabled: true
[...]
                WebserverHTTPS:
                        Enabled: true
                        Port: 1443
```

Anything that's forwarded also needs a forwarding/reverse proxy config in nginx. I think nginx by default doesn't send the original Host header when reverse proxying (mox needs the hostname to serve the correct response), and nginx buffers data by default (breaking the SSE connection from the webmail, don't forget to disable the buffering).

Unfortunately, it gets quite a bit more complicated when keeping an existing webserver...

Hope this gets you a step further!
