### ISSUE TITLE
How to provide an already existing TLS certificate and key 

### ISSUE THREAD

**Issue by pmarini** [mjl-/mox#41]
Hi,

Thanks for developing this project, I learned about this in Digital Ocean Infrastructure-as-a-Newsletter, and I'm trying it.

I'd like to know if there is a way to provide the system the TLS certificate and private key files (e.g. for Let's Encrypt would be `privkey.pem` and `fullchain.pem`) without going through the auto configuration?

**Comment by mjl-** [comment]
Yes there is! You'll have to modify config/mox.conf (you can first use the quickstart, then modify the config). Look for the "public" listener in the Listener section. Under TLS, you'll see "ACME: letsencrypt". You can remove that or comment it out. And add a "KeyCerts" instead. See https://pkg.go.dev/github.com/mjl-/mox/config#hdr-mox_conf for an example.

It may look like this:

```
Listeners:
        public:
                [...]
                TLS:
                        #ACME: letsencrypt
                        # Path to certificate and key, to be updated manually.
                        KeyCerts:
                                -
                                        CertFile: /etc/tls/wildcard.yourdomain.pem
                                        KeyFile: /etc/tls/wildcard.yourdomain-key.pem
                [...]
```

If your hostname is `mail.<yourdomain>`, you should have a TLS certificate for that domain. If you want to use autoconfig and mta-sts (the default), you'll also need a TLS certificate for `autoconfig.<yourdomain>` and `mta-sts.<yourdomain>`. If you configure additional domains for the webserver, you'll also have to add TLS certificates for them.

Hope this helps.
