### ISSUE TITLE
How to setup wildcard email?

### ISSUE THREAD

**Issue by MatthiasGrandl** [mjl-/mox#44]
Hi there! Loving mox, was up an running in minutes! Just wondering, is it possible to create wildcard email accounts that receive all emails not associated with other accounts? Kinda need this to convert from my existing setup.

**Comment by MatthiasGrandl** [comment]
works like a charm thanks!

**Comment by zigomi** [comment]
I've got this error:

    config file" err="parsing dynamic config file: :56: unknown key \"        catchall\"" pkg=mox


Here's a part of my domains.conf:

```
Accounts:
         a: <existing one.............>
              < .....................>


      catchall:
              Domain: my_domain.com
              Destinations:
                       @my_domain.com: nil

```

Any idea? @mjl-
