### ISSUE TITLE
How to combine LetsEncrypt existing certificate with "-existing-webserver"?

### ISSUE THREAD

**Issue by naddika** [mjl-/mox#94]
mox, when run with the flag `-existing-webserver`, will generate this config:

```
# public > TLS > 

KeyCerts:
        -

                # Certificate including intermediate CA certificates, in PEM format.
                CertFile: path/to/correo.domain123-chain.crt.pem

                # Private key for certificate, in PEM format. PKCS8 is recommended, but PKCS1 and
                # EC private keys are recognized as well.
                KeyFile: path/to/correo.domain123.key.pem
        -

                # Certificate including intermediate CA certificates, in PEM format.
                CertFile: path/to/mta-sts.domain123-chain.crt.pem

                # Private key for certificate, in PEM format. PKCS8 is recommended, but PKCS1 and
                # EC private keys are recognized as well.
                KeyFile: path/to/mta-sts.domain123.key.pem
        -

                # Certificate including intermediate CA certificates, in PEM format.
                CertFile: path/to/autoconfig.domain123-chain.crt.pem

                # Private key for certificate, in PEM format. PKCS8 is recommended, but PKCS1 and
                # EC private keys are recognized as well.
                KeyFile: path/to/autoconfig.domain123.key.pem
```

And these existing LetsEncrypt ones:

```
$ sudo ls -al /etc/letsencrypt/live/domain123.com
total 12
drwxr-xr-x 2 root root 4096 Nov  6 07:26 .
drwx------ 6 root root 4096 Nov  6 07:26 ..
lrwxrwxrwx 1 root root   36 Nov  6 07:26 cert.pem -> ../../archive/domain123.com/cert1.pem
lrwxrwxrwx 1 root root   37 Nov  6 07:26 chain.pem -> ../../archive/domain123.com/chain1.pem
lrwxrwxrwx 1 root root   41 Nov  6 07:26 fullchain.pem -> ../../archive/domain123.com/fullchain1.pem
lrwxrwxrwx 1 root root   39 Nov  6 07:26 privkey.pem -> ../../archive/domain123.com/privkey1.pem
-rw-r--r-- 1 root root  692 Nov  6 07:26 README
```

Which of these should I add into the `mox.conf`? There're 4 pairs in `mox.conf`. Should I remove 3 of them leaving 1? 

And for the 1 left, which 2 out of the 4 in  `/etc/letsencrypt/live/domain123.com` should I use in `mox.conf`? 

For instance, in nginx config  I'll use the `fullchain` and `privkey` one. But `mox` requires a `chain` one which is different already.
